blank_issues_enabled: false
contact_links:
    - name: Ask a question
      url: https://kite.trade/forum/
      about: Ask the community for help
    - name: Request a feature
      url: https://kite.trade/forum/
      about: Share ideas for new features
    - name: Report a bug
      url: https://github.com/zerodha/phpkiteconnect/issues/new
      about: Report a reproducable bug
